name: mitchell-prelude
version: 0.3.0

ghc-options: -Weverything

library:
  source-dirs: .
  dependencies:
    - async
    - base >= 4.9 && < 5.0
    - bytestring
    - containers
    - deepseq
    - extra
    - ghc-prim
    - microlens-platform
    - mtl
    - stm
    - text
    - transformers
    - transformers-base
    - safe-exceptions
    - unordered-containers
